<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>JS的error处理</title>
</head>
<body>

<script>
  /* 
  目标: 进一步理解JS中的错误(Error)和错误处理
    mdn文档: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Error

    1. 错误的类型
        Error: 所有错误的父类型
        ReferenceError: 引用的变量不存在
        TypeError: 数据类型不正确的错误
        RangeError: 数据值不在其所允许的范围内---递归
        SyntaxError: 语法错误
    2. 错误处理
        捕获错误: try ... catch
        抛出错误: throw error
    3. 错误对象
        message属性: 错误相关信息
        stack属性: 函数调用栈记录信息
  */

	//ReferenceError
	//console.log(a);

	//TypeError
	/* let obj = {}
	obj() */
	/* let arr = [{name:'kobe',age:18},{name:'wade',age:19}]
	let result = arr.find((item)=>{
		return item.age > 19
	})
	console.log(result.name); */


	//RangeError
	/* function demo() {
		console.log('demo');
		demo()
	}
	demo() */

	//SyntaxError
	/* function demo(params) {
		function test(params) {
			return ()=>{
	}
	demo() */

	//捕获错误
	/* 
			把可能出现错误的代码，写在try中：
				（1）若没有错误，正常执行。
				（2）若有错误，会携带错误的原因，来到catch中。
	 */
	/* try{
		let arr = [{name:'kobe',age:18},{name:'wade',age:19}]
		let result = arr.find((item)=>{
			return item.age > 19
		})
		console.log(result.name); //该行代码之行时，可能由js引擎抛出ReferenceError错误
	}
	catch(err){
		console.log('出错了',err);
	} 
	console.log(1); */


	//抛出错误
	function doSomeThing() {
		let time = Date.now()
		if(time % 2 === 1){
			console.log('时间是奇数,可以干活',time);
		}else{
			//console.log('时间是偶数,不能干活',time);
			throw(new Error('时间是偶数,不能干活'))
		}
	}

	try {
		doSomeThing()
	} catch (error) {
		console.log(error);
	}

</script>
</body>
</html>